- name: Restart webapp
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: isuride-go
    state: restarted
    daemon_reload: true
  listen: restart_webapp

- name: Restart isuride-matcher
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: isuride-matcher
    state: restarted
    daemon_reload: true
  listen: restart_webapp
