# まとめて実行用
---
# - name: Env
#  ansible.builtin.import_playbook: env.yaml
- name: Db
  ansible.builtin.import_playbook: db.yaml
- name: Web
  ansible.builtin.import_playbook: web.yaml
- name: Nginx
  ansible.builtin.import_playbook: nginx.yaml
