all:
  vars:
    tailscale_a_records: # ansibleの実行用
      S1: server1
      S2: server2
      S3: server3
    external_ips: # 外部IP あんまり使うことはないはず
      S1: 57.180.230.123
      S2: 52.68.104.24
      S3: 54.64.44.169
    internal_ips: # 内部IP サービス間の相互接続に使用
      S1: 192.168.0.11
      S2: 192.168.0.12
      S3: 192.168.0.13
    nginx_ip: "{{ internal_ips.S1 }}"
    db_ip: "{{ internal_ips.S2 }}"
    main_web_ip: "{{ internal_ips.S1 }}"
    ansible_user: isucon
  children:
    target:
      children:
        nginx:
          hosts:
            nginx01:
              ansible_host: "{{ tailscale_a_records.S1 }}"
        webapp:
          hosts:
            webapp01: # 複数デプロイする場合はwebapp02という感じで増やす
              ansible_host: "{{ tailscale_a_records.S1 }}"
        db:
          hosts:
            db:
              ansible_host: "{{ tailscale_a_records.S2 }}"
