- name: Deploy env.sh
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: isucon
    group: isucon
    mode: "0755"
  notify: restart_webapp
  with_items:
    - home/isucon/env.sh
