- name: Deploy env.sh
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: isucon
    group: isucon
    mode: "0755"
    backup: true
  notify: restart_webapp
  with_items:
    - home/isucon/env.sh
